"""db

Revision ID: 6a4cde3bbd32
Revises: 0ab26c4ebcf7
Create Date: 2022-07-13 21:41:24.473048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a4cde3bbd32'
down_revision = '0ab26c4ebcf7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
